# Generated by Django 3.1 on 2021-05-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navigationsbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='undermenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tekst', models.TextField(max_length=1000)),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undermenu', to='index.navigationsbar')),
            ],
        ),
    ]
