# Generated by Django 3.1 on 2021-05-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undermenu',
            name='tekst',
            field=models.TextField(max_length=4000),
        ),
    ]
