# Generated by Django 3.1 on 2021-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210503_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='undermenu',
            name='billede',
            field=models.ImageField(default='None', upload_to=''),
            preserve_default=False,
        ),
    ]
