# Generated by Django 3.1 on 2021-05-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_undermenu_billede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undermenu',
            name='billede',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
