# Generated by Django 3.1 on 2021-05-03 12:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210503_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undermenu',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
