# Generated by Django 3.1 on 2021-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210503_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='undermenu',
            name='billede',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
