# Generated by Django 3.1 on 2021-05-03 13:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210503_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('tekst', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('billede', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
