# Generated by Django 3.1 on 2021-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsbar',
            name='slug',
            field=models.SlugField(default='kurser', max_length=100),
            preserve_default=False,
        ),
    ]
