# Generated by Django 3.1 on 2021-05-03 15:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_navigationsbar_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tekst', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('billede', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.RemoveField(
            model_name='undermenu',
            name='relationship',
        ),
        migrations.DeleteModel(
            name='navigationsbar',
        ),
        migrations.DeleteModel(
            name='undermenu',
        ),
    ]
