# Generated by Django 3.1 on 2021-05-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_om_plakater'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='forlag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
