# Generated by Django 3.1 on 2021-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20210503_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='forlag',
            field=models.CharField(default='Sprogin', max_length=100),
            preserve_default=False,
        ),
    ]
