# Generated by Django 3.1 on 2021-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20210503_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='forlag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
