# Generated by Django 3.1 on 2021-05-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210503_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plakater',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='plakater',
            name='tekst',
        ),
    ]
