# Generated by Django 3.1 on 2021-05-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20210503_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
