# Generated by Django 3.1 on 2021-05-04 10:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_books_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
